- config/crowbarrc
- lib/crowbar/client/cli/flags.rb
The Crowbar app now runs behind apache.
> Change default port to 80

- .hound.ruby.yml
- Rakefile
- crowbar-client.gemspec
- lib/crowbar/client/cli.rb
- lib/crowbar/client/command.rb
- lib/crowbar/client/command/barclamps.rb
- lib/crowbar/client/command/batch.rb
- lib/crowbar/client/command/network.rb
- lib/crowbar/client/command/node.rb
- lib/crowbar/client/command/proposal.rb
- lib/crowbar/client/command/reset.rb
- lib/crowbar/client/command/role.rb
- lib/crowbar/client/helper.rb
- lib/crowbar/client/request.rb
- lib/crowbar/client/request/network.rb
The code is currently not DRY and I have not integrated tests yet. Hopefully we can take some time afterwards to reduce the duplication and to make it really rocksolid with tests.
**This depends on https://github.com/crowbar/crowbar-core/pull/95**
> Implemented all required network subcommands

- .hound.ruby.yml
- crowbar-client.gemspec
- lib/crowbar/client.rb
- lib/crowbar/client/cli/helper.rb
- lib/crowbar/client/cli/hooks.rb
- lib/crowbar/client/command/proposal.rb
- lib/crowbar/client/command/role.rb
- lib/crowbar/client/errors.rb
- lib/crowbar/client/filter/subset.rb
- lib/crowbar/client/formatter.rb
- lib/crowbar/client/formatter/array.rb
- lib/crowbar/client/formatter/nested.rb
- lib/crowbar/client/helper.rb
- lib/crowbar/client/request.rb
- lib/crowbar/client/request/network.rb
- lib/crowbar/client/request/node.rb
- lib/crowbar/client/request/proposal.rb
- lib/crowbar/client/util.rb
- lib/crowbar/client/util/editor.rb
The code is currently not DRY and I have not integrated tests yet. Hopefully we can take some time afterwards to reduce the duplication and to make it really rocksolid with tests.
> Implemented all required proposal subcommands

- CHANGELOG.md
- crowbar-client.gemspec
- lib/crowbar/client/app.rb
- lib/crowbar/client/app/host_ip.rb
- lib/crowbar/client/version.rb
* Fixed typos
* downgraded terminal-table dependency
* Bumped version
* Updated changelog
> Fixups for current release

- lib/crowbar/client/app/node.rb
- lib/crowbar/client/command/node/status.rb
> Added switch to node status to hide ready nodes

- lib/crowbar/client.rb
- lib/crowbar/client/app/node.rb
- lib/crowbar/client/command/base.rb
- lib/crowbar/client/command/node/list.rb
- lib/crowbar/client/command/node/status.rb
- spec/crowbar/client/command/node/list_spec.rb
This fixes https://github.com/crowbar/crowbar-client/issues/31
> Add --no-aliases and --no-names switched to node list command

- lib/crowbar/client/app.rb
- lib/crowbar/client/app/barclamp.rb
- lib/crowbar/client/app/entry.rb
- lib/crowbar/client/app/server.rb
- lib/crowbar/client/command.rb
- lib/crowbar/client/command/server.rb
- lib/crowbar/client/command/server/api.rb
- lib/crowbar/client/request.rb
- lib/crowbar/client/request/server.rb
- lib/crowbar/client/request/server/api.rb
- spec/crowbar/client/command/server/api_spec.rb
- spec/crowbar/client/request/server/api_spec.rb
> Added server api subcommand

- lib/crowbar/client/app/base.rb
- lib/crowbar/client/app/entry.rb
- lib/crowbar/client/config.rb
> Support CROWBAR_USER and CROWBAR_PASSWORD env

- lib/crowbar/client/app.rb
- lib/crowbar/client/app/entry.rb
- lib/crowbar/client/app/installer.rb
- lib/crowbar/client/command.rb
- lib/crowbar/client/command/installer.rb
- lib/crowbar/client/command/installer/start.rb
- lib/crowbar/client/command/installer/status.rb
- lib/crowbar/client/request.rb
- lib/crowbar/client/request/installer.rb
- lib/crowbar/client/request/installer/start.rb
- lib/crowbar/client/request/installer/status.rb
- spec/crowbar/client/command/installer/start_spec.rb
- spec/crowbar/client/command/installer/status_spec.rb
- spec/crowbar/client/request/installer/start_spec.rb
- spec/crowbar/client/request/installer/status_spec.rb
depends on https://github.com/crowbar/crowbar-core/pull/145
> add installer subcommand

- lib/crowbar/client/command/installer/start.rb
see https://github.com/crowbar/crowbar-core/pull/154 in commit https://github.com/crowbar/crowbar-core/commit/8ce2d6851b3d5b6ba29bb29fc2678a091594d0d3
> don't allow installation when network is not valid

- lib/crowbar/client/app.rb
- lib/crowbar/client/app/backup.rb
- lib/crowbar/client/app/entry.rb
- lib/crowbar/client/command.rb
- lib/crowbar/client/command/backup.rb
- lib/crowbar/client/command/backup/create.rb
- lib/crowbar/client/command/backup/delete.rb
- lib/crowbar/client/command/backup/download.rb
- lib/crowbar/client/command/backup/list.rb
- lib/crowbar/client/request.rb
- lib/crowbar/client/request/backup.rb
- lib/crowbar/client/request/backup/create.rb
- lib/crowbar/client/request/backup/delete.rb
- lib/crowbar/client/request/backup/download.rb
- lib/crowbar/client/request/backup/list.rb
- spec/crowbar/client/command/backup/create_spec.rb
- spec/crowbar/client/command/backup/delete_spec.rb
- spec/crowbar/client/command/backup/download_spec.rb
- spec/crowbar/client/command/backup/list_spec.rb
- spec/crowbar/client/request/backup/create_spec.rb
- spec/crowbar/client/request/backup/delete_spec.rb
- spec/crowbar/client/request/backup/download_spec.rb
- spec/crowbar/client/request/backup/list_spec.rb
* create
* download
* delete
* list
> add backup subcommand

- lib/crowbar/client/app/backup.rb
- lib/crowbar/client/app/batch.rb
- lib/crowbar/client/command/backup/download.rb
- lib/crowbar/client/command/backup/upload.rb
- lib/crowbar/client/command/batch/build.rb
- lib/crowbar/client/command/batch/export.rb
- lib/crowbar/client/command/installer/start.rb
- lib/crowbar/client/request/backup/upload.rb
- lib/crowbar/client/request/batch/build.rb
- lib/crowbar/client/request/batch/export.rb
- spec/crowbar/client/command/backup/upload_spec.rb
- spec/crowbar/client/command/batch/build_spec.rb
- spec/crowbar/client/request/batch/build_spec.rb
- spec/crowbar/client/request/batch/export_spec.rb
- spec/crowbar/client/request/proposal/create_spec.rb
- spec/crowbar/client/request/proposal/edit_spec.rb
As I messed up https://github.com/crowbar/crowbar-client/pull/55 this continues it.
> Implemented batch commands

- lib/crowbar/client/app/repository.rb
- lib/crowbar/client/command/repository/list.rb
- lib/crowbar/client/request/repository/activate.rb
- lib/crowbar/client/request/repository/deactivate.rb
- spec/crowbar/client/request/repository/activate_spec.rb
- spec/crowbar/client/request/repository/deactivate_spec.rb
the command output from repository list was broken
repositories couldn't be (de)activated
https://bugzilla.suse.com/show_bug.cgi?id=993445
> fix bsc#993445

- lib/crowbar/client/config.rb
- spec/crowbar/client/request/backup/create_spec.rb
- spec/crowbar/client/request/backup/delete_spec.rb
- spec/crowbar/client/request/backup/download_spec.rb
- spec/crowbar/client/request/backup/list_spec.rb
- spec/crowbar/client/request/backup/restore_spec.rb
- spec/crowbar/client/request/backup/upload_spec.rb
this should have been done with:
https://github.com/crowbar/crowbar-client/pull/99
> set the default version to 1.0 (again)

- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/request/upgrade/repocheck.rb
- spec/crowbar/client/command/upgrade/repocheck_spec.rb
- spec/crowbar/client/request/upgrade/repocheck_spec.rb
reuse repocheck command to not only check the addons but to check
crowbar as well.
rename addons to components to fit the new context with crowbar.
depends on:
https://github.com/crowbar/crowbar-core/pull/630
> add admin server repocheck

- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/request/upgrade/repocheck.rb
- spec/crowbar/client/command/upgrade/repocheck_spec.rb
- spec/crowbar/client/request/upgrade/repocheck_spec.rb
depends on https://github.com/crowbar/crowbar-core/pull/644
> drop ha and ceph repocheck in favor of nodes repocheck

- lib/crowbar/client.rb
- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/command/upgrade.rb
- lib/crowbar/client/command/upgrade/database.rb
- lib/crowbar/client/mixin.rb
- lib/crowbar/client/mixin/database.rb
- lib/crowbar/client/request/upgrade.rb
- lib/crowbar/client/request/upgrade/backup.rb
- lib/crowbar/client/request/upgrade/database.rb
- spec/crowbar/client/command/upgrade/database_spec.rb
- spec/crowbar/client/request/upgrade/database_spec.rb
depends on: https://github.com/crowbar/crowbar-init/pull/33
> add subcommand to set up the crowbar db during the upgrade

- lib/crowbar/client/command/upgrade/database.rb
- lib/crowbar/client/request/upgrade/database.rb
- spec/crowbar/client/request/upgrade/database_spec.rb
depends on https://github.com/crowbar/crowbar-init/pull/41
> change upgrade database url

- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/mixin/database.rb
tested with http://rubular.com/
> adapt port validation regex

- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/command/upgrade.rb
- lib/crowbar/client/command/upgrade/nodes.rb
- lib/crowbar/client/request/upgrade.rb
- lib/crowbar/client/request/upgrade/nodes.rb
- spec/crowbar/client/command/upgrade/nodes_spec.rb
- spec/crowbar/client/request/upgrade/nodes_spec.rb
in the beginning it was planned to upgrade nodes one by one, but
now the api just allows the upgrade of all nodes at once
> adapt upgrade nodes command to the api

- lib/crowbar/client/request/upgrade/repocheck.rb
- spec/crowbar/client/request/upgrade/repocheck_spec.rb
depends on https://github.com/crowbar/crowbar-core/pull/732
> adapt url's after moving the repocheck api's

- lib/crowbar/client/command/upgrade/prechecks.rb
the API response has changed, therefore we need to reformat
the output in the client as well
```bash
➜  crowbar-client git:(prechecks-format) ✗ crowbarctl upgrade prechecks    
+-------------------------------+--------+----------+------------------------+------------------------------+
| Check ID                      | Passed | Required | Errors                 | Help                         |
+-------------------------------+--------+----------+------------------------+------------------------------+
| network_checks                | false  | true     | ["error 1", "error 2"] | "Examine the error messages" |
| maintenance_updates_installed | true   | true     |                        |                              |
| compute_resources_available   | true   | false    | …
```
> reformat prechecks output

- lib/crowbar/client/command/proposal/reset.rb
- lib/crowbar/client/mixin/simple_error.rb
This change adds a new mixin which is able to format a simple error
message.
> error: Add SimpleError mixin

- lib/crowbar/client/command/upgrade/database.rb
https://github.com/crowbar/crowbar-init/pull/56
> upgrade: schema migration is included in the crowbar_init step now

- CHANGELOG.md
- lib/crowbar/client/version.rb
https://github.com/crowbar/crowbar-client/pull/135
> Bumped version to 3.1.6 and updated changelog

- CHANGELOG.md
- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/command/upgrade.rb
- lib/crowbar/client/command/upgrade/admin.rb
- lib/crowbar/client/command/upgrade/backup.rb
- lib/crowbar/client/command/upgrade/crowbar.rb
- lib/crowbar/client/command/upgrade/nodes.rb
- lib/crowbar/client/command/upgrade/prepare.rb
- lib/crowbar/client/command/upgrade/repocheck.rb
- lib/crowbar/client/command/upgrade/services.rb
- lib/crowbar/client/request/upgrade.rb
- lib/crowbar/client/request/upgrade/admin.rb
- lib/crowbar/client/version.rb
- spec/crowbar/client/command/upgrade/admin_spec.rb
- spec/crowbar/client/request/upgrade/admin_spec.rb
https://github.com/crowbar/crowbar-core/pull/981
> upgrade: internal steps were renamed to match crowbarctl subcommands

- lib/crowbar/client/command/upgrade/backup.rb
- lib/crowbar/client/command/upgrade/repocheck.rb
there is no response from the server so we need to issue a handcrafted
error message
> upgrade: Display an error when a false parameter gets passed

- lib/crowbar/client/app/upgrade.rb
- lib/crowbar/client/command/upgrade/nodes.rb
- lib/crowbar/client/request/upgrade/nodes.rb
- spec/crowbar/client/request/upgrade/nodes_spec.rb
https://github.com/crowbar/crowbar-core/pull/1056
> upgrade: Allow granular node upgrade

- lib/crowbar/client/command/upgrade/prechecks.rb
as there have been server side changes for multiple errors for a
check, we need to display them in the prechecks output as well
> upgrade: Don't show just one error

- lib/crowbar/client/request/backup/upload.rb
- spec/crowbar/client/request/backup/upload_spec.rb
Use proper args as they were changed on https://github.com/crowbar/crowbar-core/commit/7aaa2f34ae4a494248558782cfa7bfd190c38a5a
> backup: Fix upload args (bsc#1026111)

- lib/crowbar/client/app/proposal.rb
- lib/crowbar/client/command/proposal/create.rb
while creating a proposal from file
> Error if id(from file) and supplied proposal name do not match

- lib/crowbar/client/command/proposal/create.rb
proposal name from cmdline takes precedence over id(from --data option)
> proposal:Fix create proposal from json data (bsc#1037374)

- lib/crowbar/client/command/proposal/edit.rb
On crowbarctl proposal edit ... when you refer to non-existent
nodes, you should get an error which lists all the problematic
nodes.
This works with --file or --data options too.
> Display invalid nodes when editing proposal

- lib/crowbar/client/config.rb
Some upgrade commands might be different for different products being upgraded.
So let's read the system status to identify ongoing upgrade version
(if there is any) and allow user to provide specific option via ENV variable
(for the cases crowbarctl is run remotely).
> upgrade: Add an option to identify the version of product being upgraded

- lib/crowbar/client/app/backup.rb
- lib/crowbar/client/app/barclamp.rb
- lib/crowbar/client/app/installer.rb
- lib/crowbar/client/app/node.rb
- lib/crowbar/client/app/proposal.rb
- lib/crowbar/client/app/repository.rb
- lib/crowbar/client/app/role.rb
- lib/crowbar/client/app/server.rb
- lib/crowbar/client/app/upgrade.rb
The help string was incorrect.
> Fix help text for formatting options

- lib/crowbar/client/command/upgrade/repocheck.rb
Table output of repocheck subcommands was very hard to understand.
Output has been modified for better user experience.
Old format:
```
+---------------------------+----------------------------------------+
| Status                    | Value                                  |
+---------------------------+----------------------------------------+
| ha.available              | false                                  |
| ha.repos                  | SLE12-SP3-HA-Pool                      |
|                           | SLE12-SP3-HA-Updates                   |
| ha.errors.missing.x86_64  | SLE12-SP3-HA-Pool                      |
| ha.errors.inactive.x86_64 | SLE12-SP3-HA-Pool                      |
| os.available              | true                                   |
| os.repos …
```
> upgrade: Better repocheck output

- CHANGELOG.md
- lib/crowbar/client/version.rb
Depends on https://github.com/crowbar/crowbar-client/pull/187
> Release version v3.8.0

- CHANGELOG.md
- lib/crowbar/client/version.rb
Fixup last release and increment version again.
> Release 3.9.0
