.hound.ruby.yml
lib/crowbar/client/app/node.rb
lib/crowbar/client/command/node.rb
lib/crowbar/client/command/node/group.rb
lib/crowbar/client/command/node/list.rb
lib/crowbar/client/config.rb
lib/crowbar/client/mixin/barclamp.rb
lib/crowbar/client/request/node.rb
lib/crowbar/client/request/node/group.rb
spec/crowbar/client/command/node/group_spec.rb
spec/crowbar/client/command/proposal/create_spec.rb
spec/crowbar/client/command/proposal/edit_spec.rb
spec/crowbar/client/request/node/group_spec.rb

* Drop no-alias, no-name option from node list
* Added more columns to node list output
* Added option to hide meta data on node list
* Added group subcommand for nodes
~~**This pull request depends on https://github.com/crowbar/crowbar-core/pull/183 and 
https://github.com/crowbar/crowbar-core/pull/184**~~

Node subcommand improvements

---

lib/crowbar/client/request/installer/start.rb
lib/crowbar/client/request/installer/status.rb
spec/crowbar/client/request/installer/start_spec.rb
spec/crowbar/client/request/installer/status_spec.rb

The installer moved to a new path. Crowbarctl needs to be adapted.
There were no failures in mkcloud runs so far, because we trigger the installation via curl and (temporarily) support both the old and new path.

adapt to new installer path

---

lib/crowbar/client/app/entry.rb

As the short flag of --anonymous is already taken by the --alias short
flag I have renamed the short flag of --anonymous to -A

Renamed --anonymous short flag

---

lib/crowbar/client/config.rb

In large setups with many nodes, a backup creation can take more than
60 seconds
https://bugzilla.suse.com/show_bug.cgi?id=976537

bsc#976537 raise default timeout

---

.travis.yml

This changes enables the travis feature to deploy automatically
the gem to rubygems.org if a new tag is created and all tests
passes.

Enable auto deploy

---

lib/crowbar/client/app/role.rb
lib/crowbar/client/command/role/show.rb

Seems that the description and output of
role show BARCLAMP ROLE was not clear.
This patch makes it a bit clearer in both
the command help and the table header.

Clarify the command role show

---

config/crowbarrc
lib/crowbar/client/app/base.rb
lib/crowbar/client/app/entry.rb
lib/crowbar/client/config.rb
lib/crowbar/client/request/backup/create.rb
lib/crowbar/client/request/backup/delete.rb
lib/crowbar/client/request/backup/download.rb
lib/crowbar/client/request/backup/list.rb
lib/crowbar/client/request/backup/restore.rb
lib/crowbar/client/request/backup/upload.rb
lib/crowbar/client/util/apiversion.rb

The problem is that crowbar-client, as a rubygem is shared between cloud versions.
to not break the older cloud versions, we need to be able to differentiate when we have api endpoints that have changed/moved

Enable configuring the api version

---

lib/crowbar/client/command/upgrade/database.rb

and it is only one case, so it is not really necessary to use case

replace case with unless as when does not work with this negation

---

lib/crowbar/client/command/upgrade/prechecks.rb

the checks are now one level below a "checks" tree
* https://github.com/crowbar/crowbar-core/pull/744

adapt to the new api response

---

lib/crowbar/client/request/upgrade/backup.rb

an additional POST parameter is now required to determine if we
are creating the backup in an upgrade case
https://github.com/crowbar/crowbar-core/pull/770
and its yet non existing backport

adapt to the new api requirement

---

lib/crowbar/client/request/rest.rb

the default is 60 seconds, and it should be handed over as set in
crowbarctl's config.
this must have been forgotten when switching to rest-client.

hand over timeout to rest-client

---

lib/crowbar/client/command/upgrade/prechecks.rb

to not be dependent on the server response when it comes to a check
id, try to extract the check_id from the server error response.
the error response is wrapped into a check_id as well and it is safe
to extract it from there in case that it exists.
on top of that it should be insured that every error response is
wrapped into the same check_id as the top level check_id to provide
additional security. (EDIT: which is not really possible ATM, see NOTE below)
an example would be https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/app/models/api/upgrade.rb#L434
`clusters_health_crm_failures`
it is different than the `check_id` which is called `clusters_healthy` in that case
(see https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/app/models/api/upgrade.rb#L5 …

make the check_id server agnostic

---

lib/crowbar/client/command/upgrade/backup.rb
lib/crowbar/client/command/upgrade/nodes.rb
lib/crowbar/client/command/upgrade/prepare.rb
lib/crowbar/client/command/upgrade/repocheck.rb
lib/crowbar/client/command/upgrade/services.rb
lib/crowbar/client/mixin.rb
lib/crowbar/client/mixin/upgrade_error.rb
lib/crowbar/client/request/base.rb

e.message only displays the http error formatted as a string
r.response actually contains the response body
see http://www.rubydoc.info/gems/rest-client/RestClient/Exception

rest-client: use the correct api response in case of an error

---

lib/crowbar/client/command/node/rename.rb

Closing bug 1011581 - Renaming of node to already taken name via crowbarctl fails with 500 Internal Server Error.

catch error 406 when node alias is not unique

---

lib/crowbar/client/app/upgrade.rb

this must have been an unnoticed copy + paste error

upgrade: use Cancel not Prepare

---

lib/crowbar/client/command/upgrade/cancel.rb

* the server returns 422 on a failed cancel
* 423 now means that the cancel is not allowed
https://github.com/crowbar/crowbar-core/pull/881

upgrade: adapt http codes for upgrade cancel

---

lib/crowbar/client/request/upgrade/backup.rb
spec/crowbar/client/request/upgrade/backup_spec.rb

this is now in the upgrade api of crowbar-core
https://github.com/crowbar/crowbar-core/pull/946

upgrade: Change endpoint of the openstack backup

---

lib/crowbar/client/command/upgrade/backup.rb
lib/crowbar/client/command/upgrade/crowbar.rb
lib/crowbar/client/command/upgrade/database.rb
lib/crowbar/client/command/upgrade/nodes.rb
lib/crowbar/client/command/upgrade/prechecks.rb
lib/crowbar/client/command/upgrade/prepare.rb
lib/crowbar/client/command/upgrade/repocheck.rb
lib/crowbar/client/command/upgrade/services.rb

after a step has successfully finished, show the next step to execute
but only when no custom format (json|plain) is specified

upgrade: Guide user through the upgrade

---

lib/crowbar/client/command/upgrade/services.rb

Well, at least until we drop that step or make it optional...

upgrade: Next step after 'services' is openstack DB backup

---

lib/crowbar/client/command/upgrade/services.rb

otherwise it looks like `Stopping related services on all nodes.Query the upgrade status to follow the process with 'crowbarctl upgrade status'.`

upgrade: Add a space to the output of upgrade services

---

lib/crowbar/client/command/upgrade/backup.rb

The action is now (as of https://github.com/crowbar/crowbar-core/pull/1011) happening in the background.

Inform the user that OpenStack backup is ongoing.

---

lib/crowbar/client/app/upgrade.rb
lib/crowbar/client/request/upgrade/status.rb

https://github.com/crowbar/crowbar-core/pull/1062
```bash
➜  ✗ crowbarctl upgrade status nodes 
+--------------+---------------------------------+
| Status       | Value                           |
+--------------+---------------------------------+
| upgraded     |                                 |
| not_upgraded | d52-54-77-77-77-03.emil.suse.de |
|              | d52-54-77-77-77-01.emil.suse.de |
|              | d52-54-77-77-77-02.emil.suse.de |
|              | d52-54-77-77-77-04.emil.suse.de |
+--------------+---------------------------------+
```

upgrade: Enable querying the nodes upgrade status

---

lib/crowbar/client/request/base.rb

This broke requests where the body contained not string values (integers,
booleans). E.g. when trying to update a proposal using:
crowbarctl proposal edit <barclamp> default
https://bugzilla.suse.com/show_bug.cgi?id=1023834

Fix json encoding for post request (bsc#1023834)

---

lib/crowbar/client/app/upgrade.rb

This is a minor fix of https://github.com/crowbar/crowbar-client/pull/147

upgrade: Print nodes status only when nodes attribute is given

---

lib/crowbar/client/util/apiversion.rb

The v2 APIs require Accept header to be application/vnd.crowbar.v2.0+json
but the Content-Type should still be application/json for correct parsing
on server side.
This is an alternative to https://github.com/crowbar/crowbar-core/pull/1085

Fix content-type sent from crowbarctl to v2 APIs

---

lib/crowbar/client/app/entry.rb

The next maintenance update will be the enablement of the upgrade process. So no need to hide it longer.

upgrade: Remove experimental marker from upgrade subcommand

---

lib/crowbar/client/app/base.rb
lib/crowbar/client/app/entry.rb
lib/crowbar/client/config.rb
lib/crowbar/client/request/rest.rb

When we allow to deploy crowbar with https then we also have to allow to
skip the ssl verification in crowbar-client in case we use self-signed
certificates.

ssl: Allow skipping the SSL verification step

---

lib/crowbar/client/command/upgrade/repocheck.rb

The "Next step" hint was not displayed after admin repochecks.
One condition was not correct wrt last command renaming (i.e. crowbar vs admin).

upgrade: "Next step" hint after admin repochecks

---

lib/crowbar/client/config.rb

This commit syncs the timeout with all other crowbar components, it's
also the same timeout as the old CLI is using it.

Set timeout to 3600 seconds

---

.hound.suse.yml

rubocop 0.47 obsoletes the AlignWith Lint/EndAlignment
parameter and replaces it with EnforcedStyleAlignWith.

rubocop: update obsolete parameter AlignWith for Lint/EndAlignment

---

lib/crowbar/client/command/proposal/edit.rb
lib/crowbar/client/command/proposal/show.rb
lib/crowbar/client/mixin.rb
lib/crowbar/client/mixin/proposal.rb
lib/crowbar/client/request.rb
lib/crowbar/client/request/cluster.rb
lib/crowbar/client/request/cluster/list.rb
spec/crowbar/client/mixin/proposal_spec.rb
spec/crowbar/client/request/cluster/list_spec.rb

After some nodes were forgotten, crowbarctl proposal edit and show still included these in deployment list which caused failures when committing proposal. This change makes the behavior consistent with UI which filters out outdated nodes.
NOTE: this requires https://github.com/crowbar/crowbar-core/pull/1338 to provide cluster list endpoint

Add filtering of proposal deployment lists

---

lib/crowbar/client/app.rb
lib/crowbar/client/app/entry.rb
lib/crowbar/client/app/services.rb
lib/crowbar/client/command.rb
lib/crowbar/client/command/services.rb
lib/crowbar/client/command/services/clear_restart.rb
lib/crowbar/client/command/services/disable_restart.rb
lib/crowbar/client/command/services/list_restarts.rb
lib/crowbar/client/command/services/restart_flags.rb
lib/crowbar/client/request.rb
lib/crowbar/client/request/services.rb
lib/crowbar/client/request/services/clear_restart.rb
lib/crowbar/client/request/services/disable_restart.rb
lib/crowbar/client/request/services/list_restarts.rb
lib/crowbar/client/request/services/restart_flags.rb
spec/crowbar/client/command/services/clear_restart_spec.rb
spec/crowbar/client/command/services/disable_restart_spec.rb
spec/crowbar/client/command/services/list_restarts_spec.rb
spec/crowbar/client/command/services/restart_flags_spec.rb
spec/crowbar/client/request/services/clear_restart_spec.rb
spec/crowbar/client/request/services/disable_restart_spec.rb
spec/crowbar/client/request/services/list_restarts_spec.rb
spec/crowbar/client/request/services/restart_flags_spec.rb

Adds the service command and several subcommands to cover the new endpoints provided by https://github.com/crowbar/crowbar-core/pull/1307
The subcommands are as follows:
- list_restarts: List services that require a restart
- clear_restart NODE SERVICE: Clear the restart flag for a
service on a node
- restart_flags: List cookbooks and their restart
status (allowed/disallowed)
- disable_restart COOKBOOK VALUE: Set the restart
disallowed for a cookbook to true/false

crowbar: Add new service command and subcommands for service restart management

---

lib/crowbar/client/request/rest.rb
spec/crowbar/client/request/rest_spec.rb

Some characters are reserved in URIs so when used in usernames or passwords they need to be percent-escaped.

Escape reserved characters in credentials

---

lib/crowbar/client/command/database/connect.rb
lib/crowbar/client/command/database/create.rb
lib/crowbar/client/command/database/test.rb

The code was referencing the wrong variables so the default username
and password were always used. This change corrects the variable
references. Fix confirmed by sniffing the POST data and the proper
values stored in /opt/dell/crowbar_framework/config/database.yml.

Fix for custom user/pwd with 'crowbarctl database'

---

lib/crowbar/client/app/services.rb
lib/crowbar/client/request/services/clear_restart.rb
spec/crowbar/client/request/services/clear_restart_spec.rb

In the call clear_restart the parameter SERVICE is optional to allow
the restarting of all services in a node
The commit crowbar/crowbar-core#1509 and crowbar/crowbar-core#1512 are required

services: clean restart flags extended

---

lib/crowbar/client/command/node/show.rb

`crowbarctl node show help` should return error because "help" is not a node name. Instead, it currently results in a status code of 200 and outputs unwanted messages. This patch provides an easy workaround to filter the result in this special case and matches the convention used in `crowbarctl node identify help` (outputs "Node does not exist") . The correct way to show help is `crowbarctl node show --help`.
Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1024498

crowbarctl: fix 'crowbarctl node show help' wrong info

---

lib/crowbar/client/app/upgrade.rb
lib/crowbar/client/command/upgrade/nodes.rb

It is now possible to postpone upgrading the compute nodes. 
Requires https://github.com/crowbar/crowbar-core/pull/1574
**Requires** https://github.com/crowbar/crowbar-client/pull/177

upgrade: Added support for postpone/resume actions

---

lib/crowbar/client/command/upgrade/admin.rb

Database step was removed completely, next step after admin upgrade
is repository check for nodes.
**REQUIRES**  https://github.com/crowbar/crowbar-client/pull/177

upgrade: Fix the "Next step" hint after removing database step

---

lib/crowbar/client/app/upgrade.rb

(Crowbar) database step is necessary for 6 to 7 upgrade only.

upgrade: Hide the database step when it is not used

---

lib/crowbar/client/app.rb
lib/crowbar/client/app/entry.rb
lib/crowbar/client/app/ses.rb
lib/crowbar/client/command.rb
lib/crowbar/client/command/ses.rb
lib/crowbar/client/command/ses/upload.rb
lib/crowbar/client/config.rb
lib/crowbar/client/request.rb
lib/crowbar/client/request/ses.rb
lib/crowbar/client/request/ses/upload.rb
lib/crowbar/client/util/apiversion.rb
lib/crowbar/client/util/osrelease.rb

The `ses upload` subcommand can be used to upload yaml file with SES configuration to crowbar.
**NOTE** there are couple of changes included in this PR which are not strictly related to SES but rather refactoring and/or pre-requisites for actual SES commands.

ses: Add ses upload subcommand (SCRD-8432)

---

lib/crowbar/client/command/base.rb

For instance, when trying to allocate a node that is already allocated:
$ crowbarctl node allocate $node
{"error":"Node already allocated"}
It's because the JSON is actually in a RestClient::Response object. So
handle that case correctly.

Correctly parse error messages that we don't handle natively

---

lib/crowbar/client/app/proposal.rb
lib/crowbar/client/command/proposal/edit.rb
lib/crowbar/client/command/proposal/show.rb

This option allows to not automatically cleanup the proposal data, which
we usually do to remove non-existing nodes, for instance.
This is useful to see what is really in the proposal.

Add --raw to "proposal show" & "proposal edit"

---

lib/crowbar/client/app.rb
lib/crowbar/client/app/entry.rb
lib/crowbar/client/app/restricted.rb
lib/crowbar/client/command.rb
lib/crowbar/client/command/restricted.rb
lib/crowbar/client/command/restricted/allocate.rb
lib/crowbar/client/command/restricted/ping.rb
lib/crowbar/client/command/restricted/show.rb
lib/crowbar/client/command/restricted/transition.rb
lib/crowbar/client/request.rb
lib/crowbar/client/request/restricted.rb
lib/crowbar/client/request/restricted/allocate.rb
lib/crowbar/client/request/restricted/ping.rb
lib/crowbar/client/request/restricted/show.rb
lib/crowbar/client/request/restricted/transition.rb

The restricted APIs are the ones that can be used for clients with
restricted access, to do operations from insecure nodes:
crowbar_register, crowbar_join, discovery, provisioning.
This goes with https://github.com/crowbar/crowbar-core/pull/1817

Add support for the restricted APIs

---

lib/crowbar/client/command/upgrade/repocheck.rb

If some repo is only listed under "errors", the table formatter was
failing.
Example API response:
```
{
"os": {
"available": true,
"repos": [
"SLES12-SP3-Pool",
"SLES12-SP3-Updates"
],
"errors": {
}
},
"openstack": {
"available": false,
"repos": [
"SUSE-OpenStack-Cloud-Crowbar-8-Pool",
"SUSE-OpenStack-Cloud-Crowbar-8-Updates"
],
"errors": {
"missing": {
"x86_64": [
"Cloud"
]
},
"inactive": {
"x86_64": [
"Cloud"
]
}
}
}
}

upgrade: Fix repocheck table output (SOC-10718)

---

lib/crowbar/client/app/entry.rb

This is needed to backport the fix from Cloud9.

Enable restricted commands for Cloud8 (bsc#1117080)

---

lib/crowbar/client/config.rb

Depending on the environment a single chef run can take more than 15
minutes, consequently applying some barclamps (e.g. ceilometer) which
has 4 roles (meaning that chef will run 4 times) on those environments
are failing due to a timeout.

Increase the default timeout (SOC-10513)

---

lib/crowbar/client/config.rb

Turns out that changing the product timeouts are really dangerous and
it is recommended to do only on a major product version change (see: https://github.com/crowbar/crowbar-client/pull/194#issuecomment-575243669).
This reverts commit d6e0f08db5bfb026db941ff080899551b4da6366.

Revert "Increase the default timeout (SOC-10513)"

---

lib/crowbar/client/app/entry.rb

SES commands were added in 6a3465fff34665652383b731b478d1f7a3f77fe0 but were disabled for cloud versions < 9.

ses: Enable SES commands in Cloud8 (SOC-11122)

---

lib/crowbar/client/app/entry.rb

This is needed to backport the crowbar-core side changes from
Cloud 8.

Enable restricted commands for Cloud 7 (bsc#1117080)
